./test_one.sh e1
./test_one.sh e2
./test_one.sh e3
./test_one.sh e4
./test_one.sh e5
./test_one.sh e6
./test_one.sh e7
./test_one.sh e8
./test_one.sh e9
./test_one.sh e10
./test_one.sh e11
./test_one.sh e12
./test_one.sh e13
